-- Migration 004: Create exec_sql RPC Function
-- Purpose: Enable dynamic SQL execution via Supabase RPC for NL2SQL queries
-- Created: 2025-11-03

-- =============================================================================
-- CREATE exec_sql FUNCTION
-- =============================================================================
-- This function allows the Information Retrieval Agent to execute arbitrary
-- SQL queries generated by the NL2SQL pipeline (Groq LLM → SQL → Supabase)
-- =============================================================================

CREATE OR REPLACE FUNCTION exec_sql(query text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER -- Run with elevated privileges
AS $$
DECLARE
  result jsonb;
BEGIN
  -- Execute the dynamic SQL query and return results as JSONB
  EXECUTE format('SELECT jsonb_agg(row_to_json(t.*)) FROM (%s) t', query) INTO result;

  -- If no results, return empty array
  IF result IS NULL THEN
    result := '[]'::jsonb;
  END IF;

  RETURN result;

EXCEPTION
  WHEN OTHERS THEN
    -- Return error information as JSONB
    RETURN jsonb_build_object(
      'error', SQLERRM,
      'detail', SQLSTATE
    );
END;
$$;

-- =============================================================================
-- GRANT PERMISSIONS
-- =============================================================================
-- Allow authenticated users and anonymous users to execute this function
-- Adjust permissions based on your security requirements

GRANT EXECUTE ON FUNCTION exec_sql(text) TO authenticated;
GRANT EXECUTE ON FUNCTION exec_sql(text) TO anon;
GRANT EXECUTE ON FUNCTION exec_sql(text) TO service_role;

-- =============================================================================
-- COMMENT
-- =============================================================================

COMMENT ON FUNCTION exec_sql(text) IS
'Execute arbitrary SQL queries and return results as JSONB.
Used by Information Retrieval Agent for NL2SQL functionality.
Security: DEFINER mode - runs with function owner privileges.';

-- =============================================================================
-- VERIFICATION QUERY
-- =============================================================================
-- Test the function with a simple query:
-- SELECT exec_sql('SELECT id, first_name, last_name FROM candidates LIMIT 5');
